services:
  database:
    image: 'postgres:15.3-alpine'
    container_name: 'ticketz_database'
    restart: 'always'
    environment:
      POSTGRES_USER: /run/secrets/db_user
      POSTGRES_PASSWORD: /run/secrets/db_password
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    secrets:
      - db_user
      - db_password

  pg-admin:
    image: 'dpage/pgadmin4'
    container_name: 'ticketz_pgadmin'
    restart: 'always'
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: 'andre.vitor@anchieta.br'
      PGADMIN_DEFAULT_PASSWORD: /run/secrets/pgadmin_password
    secrets:
      - pgadmin_password
      - pgadmin_email
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

secrets:
  db_password:
    file: ./secrets/db_password.txt
  db_user:
    file: ./secrets/db_user.txt
  pgadmin_password:
    file: ./secrets/pgadmin_password.txt
  pgadmin_email:
    file: ./secrets/pgadmin_email.txt

# networks:
#   default:
#     name: local-network
#     external: true